import { images, videos } from "../constants";

export const pizzaList = [
  {
    id: 1,
    name: "Pizza Pepperoni",
    description: "lorem ipsum dolor sit amet",
    price: "0.005 ETH",
    data: "0x11",
    thumbnail: require("../assets/images/pizza_pep.png"),
    category: "Pizza",
  },
  {
    id: 2,
    name: "Pizza Cheese",
    description: "lorem ipsum dolor sit amet",
    price: "0.005 ETH",
    data: "0x12",
    thumbnail: require("../assets/images/pizza_cheese.png"),
    category: "Pizza",
  },
  {
    id: 3,
    name: "Pizza Mushrooms",
    description: "lorem ipsum dolor sit amet",
    price: "0.005 ETH",
    data: "0x13",
    thumbnail: require("../assets/images/pizza_mushrooms.png"),
    category: "Pizza",
  },
];

export const drinksList = [
  {
    id: 1,
    name: "Ice Lemon Tea",
    description: "lorem ipsum dolor sit amet",
    price: "0.0005 ETH",
    data: "0x31",
    thumbnail: require("../assets/images/ice-tea.png"),
    category: "Drinks",
  },
  {
    id: 2,
    name: "Coke",
    description: "lorem ipsum dolor sit amet",
    price: "0.0005 ETH",
    data: "0x32",
    thumbnail: require("../assets/images/coke.png"),
    category: "Drinks",
  },
  {
    id: 3,
    name: "Coffee",
    description: "lorem ipsum dolor sit amet",
    price: "0.0005 ETH",
    data: "0x33",
    thumbnail: require("../assets/images/coffee-cup.png"),
    category: "Drinks",
  },
];

export const dessertsList = [
  {
    id: 1,
    name: "Cheese Cake",
    description: "lorem ipsum dolor sit amet",
    price: "0.001 ETH",
    data: "0x21",
    thumbnail: require("../assets/images/cheesecake.png"),
    category: "Desserts",
  },
  {
    id: 2,
    name: "Cup Cake",
    description: "lorem ipsum dolor sit amet",
    price: "0.001 ETH",
    data: "0x22",
    thumbnail: require("../assets/images/cupcake.png"),
    category: "Desserts",
  },
  {
    id: 3,
    name: "Pudding",
    description: "lorem ipsum dolor sit amet",
    price: "0.001 ETH",
    data: "0x23",
    thumbnail: require("../assets/images/pudding.png"),
    category: "Desserts",
  },
];

export const cartLogin = [
  {
    id: 1,
    name: "Race and betting",
    price: "1,586,697.156",
    time: "01:59",
    video: require("../assets/images/last5p.png"),
    button: require("../assets/images/betting.png"),
  },
  {
    id: 2,
    name: "Campaign 1",
    price: "1,586,697.156",
    time: "01:59",
    video: require("../assets/images/last5p2.png"),
    button: require("../assets/images/view-detail.png"),
  },
  {
    id: 3,
    name: "Race and betting",
    price: "1,586,697.156",
    time: "01:59",
    video: require("../assets/images/last5p3.png"),
    button: require("../assets/images/view-detail2.png"),
  },
];

export const races = [
  {
    id: 1,
    location: [0.0, 1.0],
    color: ["#DCDCDC", "#A8A8A8"],
    colorRace: "#A8A8A8",
    imageG: require("../assets/images/class-Race/class1.png"),
    yard: require("../assets/images/Yard.png"),
    m: "1200m",
  },
  {
    id: 2,
    location: [0.0, 1.0],
    color: ["#04C5AE", "#2185BD"],
    colorRace: "#2185BD",
    imageG: require("../assets/images/class-Race/class4.png"),
    yard: require("../assets/images/Yard1.png"),
    m: "2400m",
  },
  {
    id: 3,
    location: [0.0, 1.0],
    color: ["#992DFF", "#631EAB"],
    colorRace: "#631EAB",
    imageG: require("../assets/images/class-Race/class2.png"),
    yard: require("../assets/images/Yard1.png"),
    m: "2400m",
  },
  {
    id: 4,
    location: [0.0, 1.0],
    color: ["#92CAF9", "#6791B2"],
    colorRace: "#6791B2",
    imageG: require("../assets/images/class-Race/class1.png"),
    yard: require("../assets/images/Yard1.png"),
    m: "2400m",
  },
  {
    id: 5,
    location: [0.0, 1.0],
    color: ["#DCDCDC", "#A8A8A8"],
    colorRace: "#A8A8A8",
    imageG: require("../assets/images/class-Race/class7.png"),
    yard: require("../assets/images/Yard.png"),
    m: "1200m",
  },
  {
    id: 6,
    location: [0.0, 1.0],
    color: ["#FFE32D", "#AB941E"],
    colorRace: "#AB941E",
    imageG: require("../assets/images/class-Race/class5.png"),
    yard: require("../assets/images/Yard.png"),
    m: "1200m",
  },
  {
    id: 7,
    location: [0.0, 1.0],
    color: ["#FF2D2D", "#AB1E1E"],
    colorRace: "#AB1E1E",
    imageG: require("../assets/images/class-Race/class6.png"),
    yard: require("../assets/images/Yard.png"),
    m: "1200m",
  },
  {
    id: 8,
    location: [0.0, 1.0],
    color: ["#E27808", "#B15D04"],
    colorRace: "#B15D04",
    imageG: require("../assets/images/class-Race/class2.png"),
    yard: require("../assets/images/Yard.png"),
    m: "1200m",
  },
  {
    id: 9,
    location: [0.0, 1.0],
    color: ["#E00283", "#A40060"],
    colorRace: "#A40060",
    imageG: require("../assets/images/class-Race/class3.png"),
    yard: require("../assets/images/Yard.png"),
    m: "1200m",
  },
  {
    id: 10,
    location: [0.0, 1.0],
    color: ["#92CAF9", "#6791B2"],
    colorRace: "#6791B2",
    imageG: require("../assets/images/class-Race/class2.png"),
    yard: require("../assets/images/Yard1.png"),
    m: "2400m",
  },
  {
    id: 11,
    location: [0.0, 1.0],
    color: ["#04C5AE", "#2185BD"],
    colorRace: "#2185BD",
    imageG: require("../assets/images/class-Race/class7.png"),
    yard: require("../assets/images/Yard1.png"),
    m: "2400m",
  },
  {
    id: 12,
    location: [0.0, 1.0],
    color: ["#992DFF", "#631EAB"],
    colorRace: "#631EAB",
    imageG: require("../assets/images/class-Race/class3.png"),
    yard: require("../assets/images/Yard1.png"),
    m: "2400m",
  },
];

export const dataClass = [
  { label: "All", value: "1" },
  { label: "Class 1", value: "2" },
  { label: "Class 2", value: "3" },
  { label: "Class 3", value: "4" },
  { label: "Class 4", value: "5" },
  { label: "Class 5", value: "6" },
  { label: "Class 6", value: "7" },
  { label: "Class 7", value: "8" },
  { label: "Free Style", value: "9" },
];

export const dataType = [
  { label: "All", value: "1" },
  { label: "Turf", value: "2" },
  { label: "Dirt", value: "3" },
];

export const historyCard = [
  {
    id: 1,
    dateTime: '2020-01-01 12:10 AM',
    grass: '2400m',
    server: 'MayoRNAseq',
    class: require("../assets/images/class-Race/class4.png"),
    fieldType: 'Tuft',
    entryFee: 'Free',
    prize: '3.6',
  },
  {
    id: 2,
    dateTime: '2020-03-11 12:10 AM',
    grass: '2400m',
    server: 'CHDWB',
    class: require("../assets/images/class-Race/class2.png"),
    fieldType: 'Dirt',
    entryFee: 'Free',
    prize: '16.23',
  },
  {
    id: 3,
    dateTime: '2020-06-28 07:31 AM',
    grass: '2400m',
    server: 'MSMM',
    class: require("../assets/images/class-Race/class1.png"),
    fieldType: 'Tuft',
    entryFee: 'Free',
    prize: '4.28',
  },
  {
    id: 4,
    dateTime: '2020-04-16 12:10 AM',
    grass: '2400m',
    server: 'MayoLOADGWAS',
    class: require("../assets/images/class-Race/class4.png"),
    fieldType: 'Dirt',
    entryFee: 'Free',
    prize: '3.8.19',
  },
  {
    id: 5,
    dateTime: '2020-04-17 01:23 PM',
    grass: '2400m',
    server: 'MSBB',
    class: require("../assets/images/class-Race/class7.png"),
    fieldType: 'Dirt',
    entryFee: 'Free',
    prize: '8.19',
  },
  {
    id: 6,
    dateTime: '2020-01-01 12:10 AM',
    grass: '2400m',
    server: 'MayoRNAseq',
    class: require("../assets/images/class-Race/class2.png"),
    fieldType: 'Tuft',
    entryFee: 'Free',
    prize: '3.6',
  },
  {
    id: 7,
    dateTime: '2020-01-01 12:10 AM',
    grass: '2400m',
    server: 'MayoRNAseq',
    class: require("../assets/images/class-Race/class5.png"),
    fieldType: 'Tuft',
    entryFee: 'Free',
    prize: '3.6',
  },
  {
    id: 8,
    dateTime: '2020-01-01 12:10 AM',
    grass: '2400m',
    server: 'MayoRNAseq',
    class: require("../assets/images/class-Race/class6.png"),
    fieldType: 'Tuft',
    entryFee: 'Free',
    prize: '3.6',
  },
  {
    id: 9,
    dateTime: '2020-01-01 12:10 AM',
    grass: '2400m',
    server: 'MayoRNAseq',
    class: require("../assets/images/class-Race/class3.png"),
    fieldType: 'Tuft',
    entryFee: 'Free',
    prize: '3.6',
  },
  {
    id: 10,
    dateTime: '2020-01-01 12:10 AM',
    grass: '2400m',
    server: 'MayoRNAseq',
    class: require("../assets/images/class-Race/class1.png"),
    fieldType: 'Tuft',
    entryFee: 'Free',
    prize: '3.6',
  },
  {
    id: 11,
    dateTime: '2020-01-01 12:10 AM',
    grass: '2400m',
    server: 'MayoRNAseq',
    class: require("../assets/images/class-Race/class2.png"),
    fieldType: 'Tuft',
    entryFee: 'Free',
    prize: '3.6',
  },
  {
    id: 12,
    dateTime: '2020-01-01 12:10 AM',
    grass: '2400m',
    server: 'MayoRNAseq',
    class: require("../assets/images/class-Race/class3.png"),
    fieldType: 'Tuft',
    entryFee: 'Free',
    prize: '3.6',
  },
];

export const horseList = [
  {
    id: 1,
    image: require('../assets/images/List-horse/horseWhite.png'),
    name: 'A. Baker',
    careerFirst: '17',
    careerLast: '-8/6/1',
    owner: 'B. Beats',
    background: 'rgba(0, 21, 30, 0.5)',
    odds: '6.35',
    qua: 132,
    nameUmaren: '3-1',
    oddsUmaren: '23.74',
    quaUmaren: 0,
    detail: [
      {
        id: 1,
        blood: 'Roberto',
        gender: 'Male',
        type: 'Wind',
        color: 'Yellow green',
        characteris: 'Excited',
        running_type: 'Front Runner',
        win_rates: '17.65% - 35.29%',
        speed: 'A',
        processSpeed: 0.2,
        muscle: 'S',
        processMuscle: 0.8,
        stamina: 'AAA',
        processStamina: 0.6,
        accuracy: 'AA',
        processAccuracy: 0.4,
        spirit: 'SS',
        processSpirit: 1,
        IQ: 'A',
        processIQ: 0.2
      },
    ],
  },
  {
    id: 2,
    image: require('../assets/images/List-horse/horseBlack.png'),
    name: 'J. Allen',
    careerFirst: '46',
    careerLast: '-3/2/2',
    owner: 'D. Bardsley',
    background: 'rgba(0, 21, 30, 0.75)',
    odds: '2.55',
    qua: 0,
    nameUmaren: '3-2',
    oddsUmaren: '36.26',
    quaUmaren: 0,
    detail: [
      {
        id: 2,
        blood: 'Roberto',
        gender: 'Male',
        type: 'Wind',
        color: 'Yellow green',
        characteris: 'Excited',
        running_type: 'Front Runner',
        win_rates: '17.65% - 35.29%',
        speed: 'AA',
        processSpeed: 0.4,
        muscle: 'S',
        processMuscle: 0.8,
        stamina: 'AAA',
        processStamina: 0.6,
        accuracy: 'AA',
        processAccuracy: 0.4,
        spirit: 'S',
        processSpirit: 0.8,
        IQ: 'A',
        processIQ: 0.2
      },
    ],
  },
  {
    id: 3,
    image: require('../assets/images/List-horse/horseRed.png'),
    name: 'B. Beats',
    careerFirst: '12',
    careerLast: '-5/5/8',
    owner: 'B. Beats',
    background: 'rgba(0, 21, 30, 0.5)',
    odds: '4.30',
    qua: 22,
    nameUmaren: '',
    oddsUmaren: '',
    quaUmaren: 0,
    detail: [
      {
        id: 3,
        blood: 'Roberto',
        gender: 'Male',
        type: 'Wind',
        color: 'Yellow green',
        characteris: 'Excited',
        running_type: 'Front Runner',
        win_rates: '17.65% - 35.29%',
        speed: 'A',
        processSpeed: 0.2,
        muscle: 'SS',
        processMuscle: 1,
        stamina: 'AA',
        processStamina: 0.4,
        accuracy: 'AA',
        processAccuracy: 0.4,
        spirit: 'SS',
        processSpirit: 1,
        IQ: 'A',
        processIQ: 0.2
      },
    ],
  },
  {
    id: 4,
    image: require('../assets/images/List-horse/horseLightBlue.png'),
    name: 'A. Amos',
    careerFirst: '9',
    careerLast: '-2/2/3',
    owner: 'J. Armfield',
    background: 'rgba(0, 21, 30, 0.75)',
    odds: '8.15',
    qua: 311,
    nameUmaren: '3-4',
    oddsUmaren: '46.00',
    quaUmaren: 0,
    detail: [
      {
        id: 4,
        blood: 'Roberto',
        gender: 'Male',
        type: 'Wind',
        color: 'Yellow green',
        characteris: 'Excited',
        running_type: 'Front Runner',
        win_rates: '17.65% - 35.29%',
        speed: 'A',
        processSpeed: 0.2,
        muscle: 'S',
        processMuscle: 0.8,
        stamina: 'AAA',
        processStamina: 0.6,
        accuracy: 'AA',
        processAccuracy: 0.4,
        spirit: 'SS',
        processSpirit: 1,
        IQ: 'S',
        processIQ: 0.8
      },
    ],
  },
  {
    id: 5,
    image: require('../assets/images/List-horse/horseYellow.png'),
    name: 'P. Beasley',
    careerFirst: '26',
    careerLast: '-3/2/1',
    owner: 'J. Bayliss',
    background: 'rgba(0, 21, 30, 0.5)',
    odds: '4.10',
    qua: 0,
    nameUmaren: '3-5',
    oddsUmaren: '43.49',
    quaUmaren: 0,
    detail: [
      {
        id: 5,
        blood: 'Roberto',
        gender: 'Male',
        type: 'Wind',
        color: 'Yellow green',
        characteris: 'Excited',
        running_type: 'Front Runner',
        win_rates: '17.65% - 35.29%',
        speed: 'S',
        processSpeed: 0.8,
        muscle: 'S',
        processMuscle: 0.8,
        stamina: 'S',
        processStamina: 0.8,
        accuracy: 'AA',
        processAccuracy: 0.4,
        spirit: 'SS',
        processSpirit: 1,
        IQ: 'A',
        processIQ: 0.2
      },
    ],
  },
  {
    id: 6,
    image: require('../assets/images/List-horse/horseGold.png'),
    name: 'R. Barkley',
    careerFirst: '7',
    careerLast: '-4/2/8',
    owner: 'A. Aldridge',
    background: 'rgba(0, 21, 30, 0.75)',
    odds: '6.20',
    qua: 0,
    nameUmaren: '3-6',
    oddsUmaren: '33.59',
    quaUmaren: 0,
    detail: [
      {
        id: 6,
        blood: 'Roberto',
        gender: 'Male',
        type: 'Wind',
        color: 'Yellow green',
        characteris: 'Excited',
        running_type: 'Front Runner',
        win_rates: '17.65% - 35.29%',
        speed: 'A',
        processSpeed: 0.2,
        muscle: 'S',
        processMuscle: 0.8,
        stamina: 'AAA',
        processStamina: 0.6,
        accuracy: 'AA',
        processAccuracy: 0.4,
        spirit: 'SS',
        processSpirit: 1,
        IQ: 'A',
        processIQ: 0.2
      },
    ],
  },
  {
    id: 7,
    image: require('../assets/images/List-horse/horseGreen.png'),
    name: 'N. Barmby',
    careerFirst: '33',
    careerLast: '-3/4/3',
    owner: 'C. Bastin',
    background: 'rgba(0, 21, 30, 0.5)',
    odds: '7.45',
    qua: 0,
    nameUmaren: '3-7',
    oddsUmaren: '28.29',
    quaUmaren: 0,
    detail: [
      {
        id: 7,
        blood: 'Roberto',
        gender: 'Male',
        type: 'Wind',
        color: 'Yellow green',
        characteris: 'Excited',
        running_type: 'Front Runner',
        win_rates: '17.65% - 35.29%',
        speed: 'A',
        processSpeed: 0.2,
        muscle: 'S',
        processMuscle: 0.8,
        stamina: 'AAA',
        processStamina: 0.6,
        accuracy: 'AA',
        processAccuracy: 0.4,
        spirit: 'SS',
        processSpirit: 1,
        IQ: 'A',
        processIQ: 0.2
      },
    ],
  },
  {
    id: 8,
    image: require('../assets/images/List-horse/horseGreenLight.png'),
    name: 'H. Barnet',
    careerFirst: '32',
    careerLast: '-6/2/2',
    owner: 'G. Bailey',
    background: 'rgba(0, 21, 30, 0.75)',
    odds: '3.90',
    qua: 0,
    nameUmaren: '3-8',
    oddsUmaren: '32.61',
    quaUmaren: 0,
    detail: [
      {
        id: 8,
        blood: 'Roberto',
        gender: 'Male',
        type: 'Wind',
        color: 'Yellow green',
        characteris: 'Excited',
        running_type: 'Front Runner',
        win_rates: '17.65% - 35.29%',
        speed: 'A',
        processSpeed: 0.2,
        muscle: 'S',
        processMuscle: 0.8,
        stamina: 'AAA',
        processStamina: 0.6,
        accuracy: 'AA',
        processAccuracy: 0.4,
        spirit: 'SS',
        processSpirit: 1,
        IQ: 'A',
        processIQ: 0.2
      },
    ],
  },
  {
    id: 9,
    image: require('../assets/images/List-horse/horseOrange.png'),
    name: 'T. Allen',
    careerFirst: '12',
    careerLast: '-1/2/1',
    owner: 'R. Baynham',
    background: 'rgba(0, 21, 30, 0.5)',
    odds: '1.45',
    qua: 0,
    nameUmaren: '3-9',
    oddsUmaren: '24.39',
    quaUmaren: 0,
    detail: [
      {
        id: 9,
        blood: 'Roberto',
        gender: 'Male',
        type: 'Wind',
        color: 'Yellow green',
        characteris: 'Excited',
        running_type: 'Front Runner',
        win_rates: '17.65% - 35.29%',
        speed: 'A',
        processSpeed: 0.2,
        muscle: 'S',
        processMuscle: 0.8,
        stamina: 'S',
        processStamina: 0.8,
        accuracy: 'AA',
        processAccuracy: 0.4,
        spirit: 'SS',
        processSpirit: 1,
        IQ: 'A',
        processIQ: 0.2
      },
    ],
  },
  {
    id: 10,
    image: require('../assets/images/List-horse/horseOrangeLight.png'),
    name: 'A. Ball',
    careerFirst: '6',
    careerLast: '-3/8/1',
    owner: 'G. Ashmore',
    background: 'rgba(0, 21, 30, 0.75)',
    odds: '3.20',
    qua: 0,
    nameUmaren: '3-10',
    oddsUmaren: '17.84',
    quaUmaren: 0,
    detail: [
      {
        id: 10,
        blood: 'Roberto',
        gender: 'Male',
        type: 'Wind',
        color: 'Yellow green',
        characteris: 'Excited',
        running_type: 'Front Runner',
        win_rates: '17.65% - 35.29%',
        speed: 'A',
        processSpeed: 0.2,
        muscle: 'S',
        processMuscle: 0.8,
        stamina: 'AAA',
        processStamina: 0.6,
        accuracy: 'AA',
        processAccuracy: 0.4,
        spirit: 'SS',
        processSpirit: 1,
        IQ: 'A',
        processIQ: 0.2
      },
    ],
  },
  {
    id: 11,
    image: require('../assets/images/List-horse/horseViolet.png'),
    name: 'B. Austin',
    careerFirst: '8',
    careerLast: '-3/7/1',
    owner: 'B. Austin',
    background: 'rgba(0, 21, 30, 0.5)',
    odds: '4.95',
    qua: 0,
    nameUmaren: '3-11',
    oddsUmaren: '45.77',
    quaUmaren: 0,
    detail: [
      {
        id: 11,
        blood: 'Roberto',
        gender: 'Male',
        type: 'Wind',
        color: 'Yellow green',
        characteris: 'Excited',
        running_type: 'Front Runner',
        win_rates: '17.65% - 35.29%',
        speed: 'A',
        processSpeed: 0.2,
        muscle: 'S',
        processMuscle: 0.8,
        stamina: 'AAA',
        processStamina: 0.6,
        accuracy: 'AA',
        processAccuracy: 0.4,
        spirit: 'SS',
        processSpirit: 1,
        IQ: 'A',
        processIQ: 0.2
      },
    ],
  },
  {
    id: 12,
    image: require('../assets/images/List-horse/horseVioletLight.png'),
    name: 'J. Ashcroft',
    careerFirst: '17',
    careerLast: '-8/2/6',
    owner: 'S. Bastard',
    background: 'rgba(0, 21, 30, 0.75)',
    odds: '6.80',
    qua: 0,
    nameUmaren: '3-12',
    oddsUmaren: '21.48',   
    quaUmaren: 0,
    detail: [
      {
        id: 12,
        blood: 'Roberto',
        gender: 'Male',
        type: 'Wind',
        color: 'Yellow green',
        characteris: 'Excited',
        running_type: 'Front Runner',
        win_rates: '17.65% - 35.29%',
        speed: 'A',
        processSpeed: 0.2,
        muscle: 'S',
        processMuscle: 0.8,
        stamina: 'AAA',
        processStamina: 0.6,
        accuracy: 'S',
        processAccuracy: 0.8,
        spirit: 'SS',
        processSpirit: 1,
        IQ: 'A',
        processIQ: 0.2
      },
    ],
  },
];

export const chip = [
  {
    id: 1,
    image: require('../assets/icons/chip1.png'),
    color: '#3CB0FF',
  },
  {
    id: 2,
    image: require('../assets/icons/chip3.png'),
    color: '#189803',
  },
  {
    id: 3,
    image: require('../assets/icons/chip2.png'),
    color: '#FFAE00',
  },
  {
    id: 4,
    image: require('../assets/icons/chip4.png'),
    color: '#BF04C3',
  },
];

export const round = [
  {
    id: 1,
    image: require('../assets/images/List-round/round1.png'),
  },
  {
    id: 2,
    image: require('../assets/images/List-round/round2.png'),
  },
  {
    id: 3,
    image: require('../assets/images/List-round/round3.png'),
  },
  {
    id: 4,
    image: require('../assets/images/List-round/round4.png'),
  },
  {
    id: 5,
    image: require('../assets/images/List-round/round5.png'),
  },
  {
    id: 6,
    image: require('../assets/images/List-round/round6.png'),
  },
  {
    id: 7,
    image: require('../assets/images/List-round/round7.png'),
  },
  {
    id: 8,
    image: require('../assets/images/List-round/round8.png'),
  },
  {
    id: 9,
    image: require('../assets/images/List-round/round9.png'),
  },
  {
    id: 10,
    image: require('../assets/images/List-round/round10.png'),
  },
  {
    id: 11,
    image: require('../assets/images/List-round/round11.png'),
  },
  {
    id: 12,
    image: require('../assets/images/List-round/round12.png'),
  },
];

export const noti = [
  {id: 1, title: 'What is community transmission? And how can it be prevented', time: '2020-02-29', read: false},
  {id: 2, title: "Australia's house prices hold up against the rest of the world", time: '2020-03-11', read: true},
  {id: 3, title: "Ex-intelligence official fined for retaining 'significantly sensitive' classified documents", time: '2020-02-26', read: true},
  {id: 4, title: 'What is community transmission? And how can it be prevented', time: '2020-02-29', read: false},
  {id: 5, title: "Australia's house prices hold up against the rest of the world", time: '2020-03-11', read: true},
  {id: 6, title: "Ex-intelligence official fined for retaining 'significantly sensitive' classified documents", time: '2020-02-26', read: true},
  {id: 7, title: "Australia's house prices hold up against the rest of the world", time: '2020-03-11', read: true},
  {id: 8, title: "Ex-intelligence official fined for retaining 'significantly sensitive' classified documents", time: '2020-02-26', read: true},
];

export const listAmount = [
  {
    id: 1,
    amount: 1,
  },
  {
    id: 2,
    amount: 5,
  },
  {
    id: 3,
    amount: 10,
  },
  {
    id: 4,
    amount: 20,
  },
  {
    id: 5,
    amount: 30,
  },
  {
    id: 6,
    amount: 50,
  },
  {
    id: 7,
    amount: 100,
  },
  {
    id: 8,
    amount: 'All',
  },
];

const dummyData = {
  dessertsList,
  drinksList,
  pizzaList,
  cartLogin,
  races,
  dataClass,
  dataType,
  historyCard,
  horseList,
  chip,
  round,
  noti,
  listAmount
};

export default dummyData;
